version: 2
models:

  - name: global_online_retail_cleansed
    description: 'This dataset contains the cleaned and pre-processed data of global online retail transactions, with details about each transaction, product, and customer.'
    columns:
      - name: transaction_id
        description: 'A unique identifier for each transaction, consisting of a 6-digit number. If the transaction ID starts with the letter "C", it indicates a cancellation transaction.'
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: '^C\\d{6}$|^\\d{6}$'
      - name: product_id
        description: "A not_null 5-digit number assigned to each distinct product in the retail system. This helps identify and track products in transactions."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: '^\\d{5}$'

  - name: dim_customer
    description: 'A dimension table containing customer details, used to describe customers in the transactions table.'
    columns:
      - name: customer_id
        description: 'A not_null identifier assigned to each customer in the system. This column is critical for identifying customers.'
        tests:
          - not_null
          - dbt_expectations.expect_column_distinct_count_to_equal_other_table:
              column_name: customer_id
              compare_model: ref("customer_segmentation_mart")
              compare_column_name: customer_id

  - name: dim_product
    description: 'A dimension table that holds product-related information. Each entry represents a product available for purchase in the online retail system.'
    columns:
      - name: product_id
        description: 'A not null product identifier for each item in the retail catalog.'
        tests:
          - not_null

  - name: fct_transactions
    description: 'The fact table that records all transactional details.'
    columns:
      - name: transaction_id
        description: 'A not null identifier for each transaction. It links to the transaction data in the "global_online_retail_cleansed" model.'
        tests:
          - not_null
      - name: product_unique_id
        description: 'A reference to the unique product in the "dim_product" table. This column helps identify the specific product sold in each transaction.'
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_unique_id
      - name: customer_unique_id
        description: 'A reference to the unique customer in the "dim_customer" table. This field helps identify the customer associated with each transaction.'
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_unique_id
      - name: quantity
        description: 'The quantity of the product sold in each transaction. A positive integer that represents the amount of the product bought by the customer.'
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: Number
          - positive_value
      - name: unit_price
        description: 'The price of a single unit of the product at the time of the transaction.'
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 1000
              config:
                severity: warn

  - name: customer_segmentation_mart
    description: 'A mart containing customer segmentation data, used to group customers into distinct segments based on their behavior or characteristics.'
    columns:
      - name: customer_id
        description: 'The unique identifier for each customer in the customer segmentation mart. This serves as the primary key in the mart and is used to link segmentation data with customer transactions.'
        tests:
          - not_null
          - unique
