name: dbt Tests CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  dbt_test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt

      - name: Change directory to dbt project folder
        run: cd dags/dbt/bestseller

      - name: Run dbt tests
        run: |
          dbt deps  
          dbt run 
          dbt test 
